services:
  app:
    container_name: steam-tracker-app
    build:
      context: .
      dockerfile: ./achievement-tracker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      ENV: prod
      DATABASE_URL: mysql+pymysql://root:password@db:3306/ssdb
    # depends_on:
    #   - db
    restart: unless-stopped

#   db:
#     container_name: ss-db
#     cap_add:
#       - SYS_NICE
#     image: mysql:8.0.26
#     restart: always
#     environment:
#       MYSQL_DATABASE: "ssdb"
#       MYSQL_ROOT_PASSWORD: "password"
#     expose:
#       - "3306"
#     volumes:
#       - ssdb-volume:/var/lib/mysql
# volumes:
#   ssdb-volume:
